[build]
  publish = "dist/cutelaser"
  command = "CI= ng build --prod"
[context.production]
  environment = { NODE_VERSION = "16.16.0" }
[context.deploy-preview]
  environment = { NODE_VERSION = "16.16.0" }
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200